In [1]:
import pandas as pd
import numpy as np

In [2]:
employee_identity = pd.read_csv('employee_identity.csv')
macid = pd.read_csv('final_id_3.csv')
equip_status = pd.read_csv('equip_status.csv')
equip_info = pd.read_csv('equip_info.csv')
employee_action = pd.read_csv('employee_action.csv')

In [3]:
equip_info

  EquipmentID      ClientMacAddr                 Process  ZoneID
0        P001  00:28:f8:26:ae:e4     Chemical Processing     107
1        P002  10:02:b5:e3:09:a9   Biological Fermenters     375
2        P003  18:5e:0f:ec:f0:a9        Capsule Printing     124
3        P004  28:3f:69:dc:96:85  Fill / Label / Package     360
4        P005  34:f3:9a:0e:d7:83           QA Inspection     207

In [4]:
equip_status['Priority'] = equip_status['Prority']
equip_status = equip_status.drop('Prority', axis=1)
equip_status

,EquipmentID,EquipmentState,localtime,lat,lng,Process,Level,Priority
0,P001,Hazardous Leak,2019-08-13 10:58:07,51.460469,-0.932960,Chemical Processing,3rd Floor,High
1,P002,Calibration Needed,2019-08-13 10:58:07,51.460377,-0.933075,Biological Fermenters,3rd Floor,Medium
2,P003,Normal,2019-08-13 10:58:07,51.460371,-0.932919,Capsule Printing,3rd Floor,NaN
3,P004,Regular Maintenance Needed,2019-08-13 10:58:07,51.460387,-0.932712,Fill / Label / Package,3rd Floor,Low
4,P005,Normal,2019-08-13 10:58:07,51.460489,-0.932665,QA Inspection,3rd Floor,NaN

In [5]:
equip_status = equip_status[~equip_status['Priority'].isna()]
equip_status

,EquipmentID,EquipmentState,localtime,lat,lng,Process,Level,Priority
0,P001,Hazardous Leak,2019-08-13 10:58:07,51.460469,-0.932960,Chemical Processing,3rd Floor,High
1,P002,Calibration Needed,2019-08-13 10:58:07,51.460377,-0.933075,Biological Fermenters,3rd Floor,Medium
3,P004,Regular Maintenance Needed,2019-08-13 10:58:07,51.460387,-0.932712,Fill / Label / Package,3rd Floor,Low

In [6]:
equip = pd.merge(equip_status, equip_info, on=['EquipmentID','Process'], how='left')
equip = equip[['EquipmentID', 'EquipmentState', 'localtime', 'Priority', 'Process', 'Level', 'ZoneID']]
equip

,EquipmentID,EquipmentState,localtime,Priority,Process,Level,ZoneID
0,P001,Hazardous Leak,2019-08-13 10:58:07,High,Chemical Processing,3rd Floor,107
1,P002,Calibration Needed,2019-08-13 10:58:07,Medium,Biological Fermenters,3rd Floor,375
2,P004,Regular Maintenance Needed,2019-08-13 10:58:07,Low,Fill / Label / Package,3rd Floor,360

In [7]:
macid['EquipmentID'] = macid['ClientMacAddr'].apply(lambda x: 'P001' if x=='88:64:a6:49:88:11' else 'P002' if x=='80:58:f8:5a:0d:88' else 'P004')
macid = macid.drop('Unnamed: 0', axis=1)
macid

       ClientMacAddr EquipmentID
0  88:64:a6:49:88:11        P001
1  80:58:f8:5a:0d:88        P002
2  80:58:f8:38:3c:47        P004

In [8]:
employee = pd.merge(macid, employee_identity, on='ClientMacAddr', how='left')
employee

,ClientMacAddr,EquipmentID,EmployeeID,EmployeeName,EmployeeRole,Email
0,88:64:a6:49:88:11,P001,1049,Luca Rossi,Scientist,luca.rossi@company.com
1,80:58:f8:5a:0d:88,P002,1024,Sofia Smith,Bioproduction Technologist,sofia.smith@company.com
2,80:58:f8:38:3c:47,P004,1029,Giulia Garcia,Production Operator,giulia.garcia@company.com

In [9]:
equip_employee = pd.merge(equip, employee, on='EquipmentID', how='left')
equip_employee

,EquipmentID,EquipmentState,localtime,Priority,Process,Level,ZoneID,ClientMacAddr,EmployeeID,EmployeeName,EmployeeRole,Email
0,P001,Hazardous Leak,2019-08-13 10:58:07,High,Chemical Processing,3rd Floor,107,88:64:a6:49:88:11,1049,Luca Rossi,Scientist,luca.rossi@company.com
1,P002,Calibration Needed,2019-08-13 10:58:07,Medium,Biological Fermenters,3rd Floor,375,80:58:f8:5a:0d:88,1024,Sofia Smith,Bioproduction Technologist,sofia.smith@company.com
2,P004,Regular Maintenance Needed,2019-08-13 10:58:07,Low,Fill / Label / Package,3rd Floor,360,80:58:f8:38:3c:47,1029,Giulia Garcia,Production Operator,giulia.garcia@company.com

In [10]:
equip_employee_action = pd.merge(equip_employee, employee_action, on=['EmployeeRole', 'Process', 'EquipmentState', 'Priority'], how='left')
equip_employee_action

,EquipmentID,EquipmentState,localtime,Priority,Process,Level,ZoneID,ClientMacAddr,EmployeeID,EmployeeName,EmployeeRole,Email,Action
0,P001,Hazardous Leak,2019-08-13 10:58:07,High,Chemical Processing,3rd Floor,107,88:64:a6:49:88:11,1049,Luca Rossi,Scientist,luca.rossi@company.com,• Ring alarm\n• Email / Text\n• Shutdown
1,P002,Calibration Needed,2019-08-13 10:58:07,Medium,Biological Fermenters,3rd Floor,375,80:58:f8:5a:0d:88,1024,Sofia Smith,Bioproduction Technologist,sofia.smith@company.com,• Notice of schedule
2,P004,Regular Maintenance Needed,2019-08-13 10:58:07,Low,Fill / Label / Package,3rd Floor,360,80:58:f8:38:3c:47,1029,Giulia Garcia,Production Operator,giulia.garcia@company.com,• Refresh Maintenance Log

In [13]:
def employee_email_content (equip_employee_action):
    for i, row in equip_employee_action.iterrows():
        print('Send to:' + row['Email'])
        employee = f"Dear {row['EmployeeRole']} {row['EmployeeName']}, \n"
        print(employee)
        alert = f"The state of equipment ({row['EquipmentID']}) changes to {row['EquipmentState']} at {row['localtime']}."
        print(alert)
        print('The priority is ' + row['Priority'] + '.')
        location = f"The location is {row['Level']}, and the zone id is {row['ZoneID']}."
        print(location)
        action = f"What you need to do is the following step(s): \n{row['Action']} \n"
        print(action)
        print('Please investigate on-site as soon as possible! \n\n')

In [14]:
employee_email_content(equip_employee_action)

Send to:luca.rossi@company.com
Dear Scientist Luca Rossi,

The state of equipment (P001) changes to Hazardous Leak at 2019-08-13 10:58:07.
The priority is High.
The location is 3rd Floor, and the zone id is 107.
What you need to do is the following step(s):
• Ring alarm
• Email / Text
• Shutdown

Please investigate on-site as soon as possible!


Send to:sofia.smith@company.com
Dear Bioproduction Technologist Sofia Smith,

The state of equipment (P002) changes to Calibration Needed at 2019-08-13 10:58:07.
The priority is Medium.
The location is 3rd Floor, and the zone id is 375.
What you need to do is the following step(s):
• Notice of schedule

Please investigate on-site as soon as possible!


Send to:giulia.garcia@company.com
Dear Production Operator Giulia Garcia,

The state of equipment (P004) changes to Regular Maintenance Needed at 2019-08-13 10:58:07.
The priority is Low.
The location is 3rd Floor, and the zone id is 360.
What you need to do is the following step(s):
• Refresh Maintenance Log

Please investigate on-site as soon as possible!