In [1]:
import pandas as pd
import numpy as np

In [2]:
device = pd.read_csv('test1.csv')
employee_identity = pd.read_csv('employee_identity.csv')
macid = pd.read_csv('final_id.csv')
camera = pd.read_csv('camera.csv')
photo = pd.read_csv('photo.csv')

In [3]:
photo

  Camera ID                    photo                 time
0   camera1  IMG_20190813_001007.JPG  2019-08-13 00:10:07
1   camera1  IMG_20190813_002017.JPG  2019-08-13 00:20:17

In [4]:
device

,ClientMacAddr,time,recheck_time,SecurityArea,localtime,Site,Level,lat,lng,ZoneID
0,d0:e4:0b:fb:a2:6c,2019-08-13 00:20:17,2019-08-13 00:30:17,data_center,2019-08-13 00:20:17,UK Office,3rd Floor,51.460521,-0.932417,308

In [5]:
macid

   Unnamed: 0      ClientMacAddr
0           0  4c:56:9d:75:d1:e5

In [6]:
employee_identity

,EmployeeID,EmployeeName,EmployeeRole,Email,ClientMacAddr
0,1029,Giulia Garcia,Production Operator,giulia.garcia@company.com,80:58:f8:38:3c:47
1,1013,Roberto Gutierrez,Security Guard,roberto.gutierrez@company.com,08:f6:9c:14:24:1b
2,1018,Marta Greco,Manufacturing Tech,marta.greco@company.com,1c:56:fe:09:23:62
3,1027,Miku Pérez,Security Guard,miku.pérez@company.com,0c:51:01:b3:88:92
4,1024,Sofia Smith,Bioproduction Technologist,sofia.smith@company.com,80:58:f8:5a:0d:88
5,1008,Lorenzo Garcia,Scientist,lorenzo.garcia@company.com,88:b4:a6:49:88:11
6,1038,Maria Castillo,Bioproduction Technologist,maria.castillo@company.com,80:58:f8:0a:f3:13
7,1021,Sergio Bianchi,Security Guard,sergio.bianchi@company.com,0c:51:01:c9:bc:12
8,1032,Haruka Martinez,Scientist,haruka.martinez@company.com,80:58:f8:bf:df:ff
9,1048,Sofia Rizzo,Production Operator,sofia.rizzo@company.com,80:58:f8:2b:14:34
10,1050,Yuta Gallo,Facility Manager,yuta.gallo@company.com,80:58:f8:3d:ef:0f
11,1049,Luca Rossi,Scientist,luca.rossi@company.com,88:64:a6:49:88:11
12,1008,Ludovica Yamamoto,Production Operator,ludovica.yamamoto@company.com,80:58:f8:56:3f:5f
13,1006,Emily Ricci,Bioproduction Technologist,emily.ricci@company.com,80:58:f8:13:b2:d2
14,1009,Ava Fernandez,Production Operator,ava.fernandez@company.com,80:58:f8:95:47:67
15,1041,Chen Gomez,Bioproduction Technologist,chen.gomez@company.com,80:58:f8:32:1b:3b
16,1027,Luca García,Bioproduction Technologist,luca.garcía@company.com,80:58:f8:84:6d:8d
17,1031,Olivia Gutierrez,Scientist,olivia.gutierrez@company.com,80:58:f8:5f:48:68
18,1002,Chen Nakamura,Manufacturing Tech,chen.nakamura@company.com,80:58:f8:d1:f1:11
19,1032,Yuta Russo,Bioproduction Technologist,yuta.russo@company.com,80:58:f8:87:70:90
20,1009,Olivia Yamamoto,Production Operator,olivia.yamamoto@company.com,80:58:f8:bf:a8:c8
21,1014,Sara Rodriguez,Security Guard,sara.rodriguez@company.com,24:1b:7a:b1:f2:ef
22,1019,Francesco Tanaka,Manufacturing Tech,francesco.tanaka@company.com,80:58:f8:4b:c8:b1
23,1015,Luisa Moreno,Production Operator,luisa.moreno@company.com,80:58:f8:99:82:a2
24,1011,Isabella Silva,Bioproduction Technologist,isabella.silva@company.com,80:58:f8:00:e9:09
25,1017,John Okada,Facility Manager,john.okada@company.com,80:58:f8:0a:85:37
26,1004,Lorenzo Rizzo,Scientist,lorenzo.rizzo@company.com,80:58:f8:48:68:88
27,1030,Paola Sánchez,Production Operator,paola.sánchez@company.com,80:58:f8:02:b4:d4
28,1040,Isabella Bianchi,Security Guard,isabella.bianchi@company.com,28:cf:e9:2d:5d:b5
29,1007,Yuki Yamamoto,Security Guard,yuki.yamamoto@company.com,4c:56:9d:75:d1:e5
30,1021,Lucia Davis,Security Guard,lucia.davis@company.com,5c:ad:cf:c2:25:b8
31,1002,Yuki Ricci,Manufacturing Tech,yuki.ricci@company.com,80:58:f8:fe:e7:07
32,1046,Luisa Bianchi,Production Operator,luisa.bianchi@company.com,80:58:f8:77:4d:6d
33,1019,Kaito Russo,Manufacturing Tech,kaito.russo@company.com,80:58:f8:17:00:20
34,1040,Paola Moretti,Scientist,paola.moretti@company.com,80:58:f8:a4:d5:ab
35,1046,Pedro Ferrari,Manufacturing Tech,pedro.ferrari@company.com,80:58:f8:c4:ad:cd
36,1002,Francesco Hernandez,Production Operator,francesco.hernandez@company.com,80:58:f8:ac:4b:6b
37,1038,Paola Yamamoto,Scientist,paola.yamamoto@company.com,80:58:f8:0c:f5:15
38,1003,Ricardo Marino,Scientist,ricardo.marino@company.com,80:58:f8:dc:c5:e5
39,1041,Alejandro Ortega,Manufacturing Tech,alejandro.ortega@company.com,80:58:f8:ae:97:b7
40,1000,Aki Gonzalez,Manufacturing Tech,aki.gonzalez@company.com,80:58:f8:de:c7:e7
41,1007,Marta Lopez,Security Guard,marta.lopez@company.com,80:e6:50:5e:1f:85
42,1046,Arianna Lombardi,Facility Manager,arianna.lombardi@company.com,80:58:f8:1c:05:25
43,1021,Kaito Davis,Scientist,kaito.davis@company.com,80:58:f8:de:fe:1e
44,1028,Ludovica Romano,Manufacturing Tech,ludovica.romano@company.com,80:58:f8:54:08:f1
45,1048,Natsumi Yamamoto,Scientist,natsumi.yamamoto@company.com,80:58:f8:a1:8a:aa
46,1010,Pedro Fernandez,Bioproduction Technologist,pedro.fernandez@company.com,80:58:f8:a0:52:72
47,1023,Juan Johnson,Manufacturing Tech,juan.johnson@company.com,80:58:f8:e2:cb:eb
48,1023,Kaito Bianchi,Scientist,kaito.bianchi@company.com,80:58:f8:e3:03:23
49,1017,Juanita Silva,Manufacturing Tech,juanita.silva@company.com,80:58:f8:26:0f:2f

In [7]:
security_guard = employee_identity[employee_identity['ClientMacAddr'].isin(macid['ClientMacAddr'])]
security_guard

,EmployeeID,EmployeeName,EmployeeRole,Email,ClientMacAddr
29,1007,Yuki Yamamoto,Security Guard,yuki.yamamoto@company.com,4c:56:9d:75:d1:e5

In [8]:
device

,ClientMacAddr,time,recheck_time,SecurityArea,localtime,Site,Level,lat,lng,ZoneID
0,d0:e4:0b:fb:a2:6c,2019-08-13 00:20:17,2019-08-13 00:30:17,data_center,2019-08-13 00:20:17,UK Office,3rd Floor,51.460521,-0.932417,308

In [9]:
def security_email_content (security_guard, device):
    for i, row in security_guard.iterrows():
        print('Send to:' + row['Email'])
        employee_message = f"Dear {row['EmployeeName']}, \n"
        print(employee_message)
    for i, row in device.iterrows():
        alert_message = f"An unauthorized device ({row['ClientMacAddr']}) appears in the {row['SecurityArea']} at {row['time']}. \nThe location is {row['Level']}, and the zone id is {row['ZoneID']}.\n"
        print(alert_message)
        print('Please investigate on-site as soon as possible!')

In [10]:
def attach_photo(device, camera, photo):
    find_camera = pd.merge(device, camera, on='SecurityArea')
    find_photo = pd.merge(find_camera, photo, on=["time","Camera ID"])
    print(find_photo["photo"][0])

In [11]:
security_email_content(security_guard, device)

Send to:yuki.yamamoto@company.com
Dear Yuki Yamamoto,

An unauthorized device (d0:e4:0b:fb:a2:6c) appears in the data_center at 2019-08-13 00:20:17.
The location is 3rd Floor, and the zone id is 308.

Please investigate on-site as soon as possible!

In [12]:
attach_photo(device, camera, photo)

IMG_20190813_002017.JPG